language: nix
script: |
  bash -c '
    set -e
    set -x

    gopath_location="$HOME/projects/src/github.com/corpix/formats"
    mkdir -p "$(dirname "$gopath_location")"
    [ -e "$gopath_location" ] || ln -s $(pwd) "$gopath_location"
    cd "$gopath_location"

    nixpkgs_rev=03050e9749e1548f1648aae5c062c954eaad546e
    curl -L https://github.com/NixOS/nixpkgs/archive/${nixpkgs_rev}.tar.gz | tar -xz -C $HOME
    export NIX_PATH=nixpkgs=$HOME/nixpkgs-${nixpkgs_rev}

    unset GOROOT
    unset GOPATH

    nix-shell --command "make test"
  '

cache:
  directories:
    - /nix
